framework:
    secret: '%env(APP_SECRET)%'

    # Configuration de la session
    session: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file